### PR TITLE
replace GTK_STOCK_CANCEL with _Cancel

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by monsta** [comment]
This will probably drop the icon from the button as a side effect...

**Comment by sc0w** [comment]
yes, with this PR we loss the cancel icon

please test https://github.com/mate-desktop/mate-polkit/pull/49

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-polkit/pull/49 works, the difference is it explicitly sets the icon. That could have been done with a second commit to this PR but since we have a new one this one should probably be closed.

**Comment by yetist** [comment]
@sc0w @lukefromdc 

Good, I close this PR, please use #49.

**Pull request closed without merging**
