### PR TITLE
Add meson compilation support

### PR DESCRIPTION
**Pull request by zhuyaliang**
## test
```
meson setup _build --prefix=/usr

ninja -C _build

meson install -C _build
```

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
When building with meson, installation worked, authorization of mounting internal devices worked,but documentation (/usr/share/doc/mate-polkit) was NOT installed

**Comment by zhuyaliang** [comment]
@lukefromdc 
add documentation when building rpm packages

[mate-polkit.spec](https://src.fedoraproject.org/rpms/mate-polkit/blob/rawhide/f/mate-polkit.spec#_88)

**Comment by lukefromdc** [comment]
I'm working with Debian Unstable, not Fedora so that will be different. Docs installing OK on other meson packages.

**Comment by zhuyaliang** [comment]
```
make install DESTDIR=/tmp/polkit-make
DESTDIR=/tmp/common-meson ninja -C build/ install

[test@localhost mate-polkit]$ ls /tmp/polkit-make/usr/share
locale
[test@localhost mate-polkit]$ ls /tmp/polkit-meson/usr/share/
locale
[test@localhost mate-polkit]$ find /tmp/polkit-make/usr/share | wc -l
332
[test@localhost mate-polkit]$ find /tmp/polkit-meson/usr/share | wc -l
332
[test@localhost mate-polkit]$ 
```
The doc directory is added by ```Debian``` and ```Fedora``` maintainer

**Comment by lukefromdc** [comment]
Sorry, in my autotools builds done WITHOUT any patches from Debian, /usr/share/doc/mate-common is always installed. I won't merge this without either this being fixed or a vote for it from another maintainer as I am opposed to changing this default.

**Comment by lukefromdc** [comment]
I just found something interesting: Checkinstall provides an option to install the files in /usr/share/doc-and in fact they do NOT get installed by make install so you have in fact matched the behavior of autotools. Will merge.

What I had never noticed was that on some packages make install does not install them. I have hand packed my custom changelogs into /usr/share/doc copied from previous packages so long I never noticed until now that I was not having to overwrite or add to a default set of docs files. Probably none of the mate packages I have would have included them by default

Pardon the hassle

**Pull request merged**
