### PR TITLE
drop polkitgtkmate library and its docs

### PR DESCRIPTION
**Pull request by monsta**
it contains only PolkitLockButton widget which nobody uses by now
and GTK+3 already has GtkLockButton

same as done upstream long ago:
https://git.gnome.org/browse/PolicyKit-gnome/commit/?id=1340926a935b60b2b605a8d0d9b256e3a83c3d7d
https://git.gnome.org/browse/PolicyKit-gnome/commit/?id=b8d700121941bb1f032b95c428d2e52a11c5d330

### CODE REVIEW

**Comment by monsta** [comment]
Yes, the polkit agent executable should work as before. It doesn't use this library. The library is only needed when you want to place an "unlock privileges" button in your app, but now there's GtkLockButton for that.

**Comment by lukefromdc** [comment]
Do any of our applications (such as configuring the panel clock) that have such an unlock button use the old PolkitLockButton widget? If not we should be able to drop this without issue

**Comment by monsta** [comment]
No, our apps don't use it.

**Comment by lukefromdc** [comment]
Than this should be ready to go

**Pull request merged**
