### PR TITLE
drop deprecated gtk_dialog_get_action_area

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by raveit65** [comment]
I seems to be working, but i am still wondering why the GtkButtonBox around the buttons called `action_area` in gtk3-inspector?
Bildschirmfoto zu 2019-07-05 10-37-44
And yes, i tested that several times that my rpm use the commit.
As you can see the other commit which remove `gtk-cancel` from button works well.

**Comment by yetist** [comment]
The "action-area-border" and "button-spacing" style properties should set through themes css file.

https://developer.gnome.org/gtk3/stable/GtkDialog.html#GtkDialog--s-action-area-border
https://developer.gnome.org/gtk3/stable/GtkDialog.html#GtkDialog--s-button-spacing

**Comment by raveit65** [comment]
Yes, we have that in themes, but why i see the GtkButtonBox name `action_area in inspector.
I mean you removed that widget in commit.
Or does this come directly from GtkDialog?

**Comment by yetist** [comment]
I think it come from GtkDialog.

**Pull request merged**
