### PR TITLE
Switch to Ayatana AppIndicator.

### PR DESCRIPTION
**Pull request by sunweaver**
We are currently in the process of making Indicators available to all *nix platforms, not only Ubuntu.

For this, please consider merging this PR. After the merge, mate-polkit will work just fine on Ubuntu. No need to switch to Ayatana Indicators on the rendering level.

### CODE REVIEW

**Comment by raveit65** [comment]
How should that work with distros from the dark side :) ?
```
[rave@mother ~]$ dnf provides */libayatana-appindicator/app-indicator.h
RPM Fusion for Fedora 26 - Free - Updates       2.9 MB/s | 493 kB     00:00    
RPM Fusion for Fedora 26 - Free                 2.1 MB/s | 519 kB     00:00    
RPM Fusion for Fedora 26 - Nonfree - Updates    728 kB/s |  60 kB     00:00    
RPM Fusion for Fedora 26 - Nonfree              1.0 MB/s | 158 kB     00:00    
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:00 am Do 29 Mär 2018 13:27:08 CEST.
Fehler: Keine Übereinstimmungen gefunden
[rave@mother ~]$ yum-deprecated provides */libayatana-appindicator/app-indicator.h
Yum command has been deprecated, use dnf instead.
See 'man dnf' and 'man yum2dnf' for more information.

fedora/26/x86_64/metalink                                   |  26 kB  00:00     
rpmfusion-free/26/x86_64/metalink                           |  10 kB  00:00     
rpmfusion-nonfree/26/x86_64/metalink                        |  10 kB  00:00     
MEGAsync                                                                  14/14
MEGAsync/26/filelists                                       | 7.6 kB  00:00     
results/filelists_db                                        | 942 kB  00:00     
results-mate-1.20/filelists_db                              | 893 kB  00:00     
results-mate-1.22/filelists_db                              |  30 kB  00:00     
results-rpmfusion_all/filelists_db                          |  75 kB  00:00     
rpmfusion-free-updates/26/x86_64/filelists_db               | 302 kB  00:00     
rpmfusion-nonfree-updates/26/x86_64/filelists_db            |  36 kB  00:00     
updates/26/x86_64/filelists_db                              |  15 MB  00:02     
No matches found
```

**Comment by sunweaver** [comment]
Hi Wolfang,

On  Do 29 Mär 2018 13:30:10 CEST, raveit65 wrote:

> How should that work with distros from the dark side :) ?
> ```
> [rave@mother ~]$ dnf provides */libayatana-appindicator/app-indicator.h
> RPM Fusion for Fedora 26 - Free - Updates       2.9 MB/s | 493 kB     00:00
> RPM Fusion for Fedora 26 - Free                 2.1 MB/s | 519 kB     00:00
> RPM Fusion for Fedora 26 - Nonfree - Updates    728 kB/s |  60 kB     00:00
> RPM Fusion for Fedora 26 - Nonfree              1.0 MB/s | 158 kB     00:00
> Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:00 am Do 29 Mär  
> 2018 13:27:08 CEST.
> Fehler: Keine Übereinstimmungen gefunden
> [rave@mother ~]$ yum-deprecated provides  
> */libayatana-appindicator/app-indicator.h
> Yum command has been deprecated, use dnf instead.
> See 'man dnf' and 'man yum2dnf' for more information.
>
> fedora/26/x86_64/metalink                                   |  26 kB  00:00
> rpmfusion-free/26/x86_64/metalink                           |  10 kB  00:00
> rpmfusion-nonfree/26/x86_64/metalink                        |  10 kB  00:00
> MEGAsync                                                              
>      14/14
> MEGAsync/26/filelists                                       | 7.6 kB  00:00
> results/filelists_db                                        | 942 kB  00:00
> results-mate-1.20/filelists_db                              | 893 kB  00:00
> results-mate-1.22/filelists_db                              |  30 kB  00:00
> results-rpmfusion_all/filelists_db                          |  75 kB  00:00
> rpmfusion-free-updates/26/x86_64/filelists_db               | 302 kB  00:00
> rpmfusion-nonfree-updates/26/x86_64/filelists_db            |  36 kB  00:00
> updates/26/x86_64/filelists_db                              |  15 MB  00:02
> No matches found
> ```

See my latest post on https://sunweavers.net.

I recommend bringing libayatana-appindicator to the dark distros and  
give them light.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by lukefromdc** [comment]
Reality is those on any particular distro will need to either use the indicator support their distro ships. I see Debian is switching over we we will need this, but we should not remove the existing support until all distros have switched over

**Comment by sunweaver** [comment]
Hi,

On  Do 29 Mär 2018 19:43:59 CEST, lukefromdc wrote:

> Reality is those on any particular distro will need to either use  
> the indicator support their distro ships. I see Debian is switching  
> over we we will need this, but we should not remove the existing  
> support until all distros have switched over

I have pushed a second commit to the PR branch that adds back Ubuntu  
AppIndicator support as fallback if Ayatana AppIndicator is not present.

Greets,
Mike

-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by lukefromdc** [comment]
OK, that's exactly what we need while distros transition

**Comment by lukefromdc** [comment]
I just installed Ayatana indicator support, and built this. Build supports both indicator formats, so I don't know which one it is using but it works without issue

**Comment by sunweaver** [comment]
Hi

On  Fr 30 Mär 2018 23:50:28 CEST, lukefromdc wrote:

> I just installed Ayatana indicator support, and built this. Build  
> supports both indicator formats, so I don't know which one it is  
> using but it works without issue

Ayatana Indicators are preferred, if present. Use ldd on the  
polkit-1-mate-auth-agent (or what's its name) executable to see what  
it is linked against (libayatana-appindicator or libappindicator).

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by lukefromdc** [comment]
OK, looks like it works: I got
libayatana-appindicator3.so.1 => /usr/lib/x86_64-linux-gnu/libayatana-appindicator3.so.1 (0x00007f17fcea0000)

**Comment by monsta** [comment]
Hmm... did you fork/rename libappindicator as well?

For the forks of indicators themselves, like indicator-application or indicator-sound, only indicator panel applets (in MATE or Xfce or other desktops) had to be adjusted. For the fork of the library you'll have to patch a lot more apps that make use of it...

**Comment by sunweaver** [comment]
Hi,

On Sunday, April 1, 2018, monsta wrote:
> Hmm... did you fork/rename libappindicator as well?
> For the forks of indicators themselves, like indicator-application or indicator-sound, only indicator panel applets (in MATE or Xfce or other desktops) had to be adjusted. For the fork of the library you'll have to patch a lot more apps that make use of it... 

Yes, the full indicator stack got forked, including libayatana-appindicator. The libayatan-indicator is the problematic shared lib regarding GTK, Ido and rendering. So we needed to fork appindicator shared lib, too.

Mike
-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by lukefromdc** [comment]
Any updates on this?

**Comment by lukefromdc** [comment]
Note that this no longer builds as-is on Debian, as it predates the initltool->gettext transition and the older system is no longer supported.

**Comment by lukefromdc** [comment]
The web editor did something ugly: in trying to fix conflicts by replacing configure.ac and src/makefile.am, it instead merged the entire master branch back into the PR branch, though as a 3ed commit that the originator can revert. CLOSING this and making a new PR instead with the changes from this to support both indicator types hand-edited into the current build system

**Comment by lukefromdc** [comment]
Follow-on PR based on current master at
https://github.com/mate-desktop/mate-polkit/pull/70

**Pull request closed without merging**
